### ISSUE TITLE
Error when used as a submodule

### ISSUE THREAD

**Issue by oleorhagen** [lepture/mistune#215]
# Commands run

```
git submodule add git@github.com:lepture/mistune.git mistune
```
```
python3 -c 'from mistune import mistune
```

# Output
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/olepor/go/src/github.com/mendersoftware/mender-hub/mistune/mistune/__init__.py", line 6, in <module>
    from .plugins import PLUGINS
  File "/home/olepor/go/src/github.com/mendersoftware/mender-hub/mistune/mistune/plugins/__init__.py", line 1, in <module>
    from .extra import plugin_url, plugin_strikethrough
  File "/home/olepor/go/src/github.com/mendersoftware/mender-hub/mistune/mistune/plugins/extra.py", line 1, in <module>
    from mistune.scanner import escape_url
ModuleNotFoundError: No module named 'mistune.scanner'
```

**Comment by oleorhagen** [comment]
I'm not a Pythonista, so this is just what I find to be unexpected behaviour. So, is this wrong or not?

**Comment by lepture** [comment]
You need to install it at first:

```
pip install .
```
