### ISSUE TITLE
2.0.2: not ready for sphinx 5.0.x

### ISSUE THREAD

**Issue by kloczek** [lepture/mistune#310]
On building `nbconvert` documentation fount that `mistune` is not ready to be used with latest `sphinx` 5.0.1
```console
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v5.0.1

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/docs/source/conf.py", line 25, in <module>
    exec(compile(f.read(), "autogen_config.py", "exec"), {})
  File "autogen_config.py", line 12, in <module>
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/nbconvert/__init__.py", line 3, in <module>
    from . import filters, postprocessors, preprocessors, writers
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/nbconvert/filters/__init__.py", line 8, in <module>
    from .markdown import *
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/nbconvert/filters/markdown.py", line 13, in <module>
    from .markdown_mistune import markdown2html_mistune
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/nbconvert/filters/markdown_mistune.py", line 37, in <module>
    class MathBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 356, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/docs/source/conf.py", line 25, in <module>
    exec(compile(f.read(), "autogen_config.py", "exec"), {})
  File "autogen_config.py", line 12, in <module>
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/nbconvert/__init__.py", line 3, in <module>
    from . import filters, postprocessors, preprocessors, writers
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/nbconvert/filters/__init__.py", line 8, in <module>
    from .markdown import *
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/nbconvert/filters/markdown.py", line 13, in <module>
    from .markdown_mistune import markdown2html_mistune
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/nbconvert/filters/markdown_mistune.py", line 37, in <module>
    class MathBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/docs/source/conf.py", line 25, in <module>
    exec(compile(f.read(), "autogen_config.py", "exec"), {})
  File "autogen_config.py", line 12, in <module>
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/nbconvert/__init__.py", line 3, in <module>
    from . import filters, postprocessors, preprocessors, writers
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/nbconvert/filters/__init__.py", line 8, in <module>
    from .markdown import *
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/nbconvert/filters/markdown.py", line 13, in <module>
    from .markdown_mistune import markdown2html_mistune
  File "/home/tkloczko/rpmbuild/BUILD/nbconvert-6.5.0/nbconvert/filters/markdown_mistune.py", line 37, in <module>
    class MathBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar'
```

**Comment by kloczek** [comment]
I've I've retested build, install and `mistune` test suite and in build env with `sphinx 5.0.1 all passes correctly.
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-mistune-2.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-mistune-2.0.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/mistune-2.0.2
plugins: cov-3.0.0, dependency-0.5.1
collected 561 items

tests/test_ast.py .............                                                                                                                                      [  2%]
tests/test_commonmark.py ........................................................................................................................................... [ 27%]
.................................................................................................................................................................... [ 56%]
..........................................................................................................................                                           [ 78%]
tests/test_directive.py ........                                                                                                                                     [ 79%]
tests/test_include.py ...                                                                                                                                            [ 80%]
tests/test_misc.py .........                                                                                                                                         [ 81%]
tests/test_plugins.py ..................................................                                                                                             [ 90%]
tests/test_syntax.py .........................................                                                                                                       [ 97%]
tests/test_toc.py ............                                                                                                                                       [100%]

=========================================================================== 561 passed in 0.94s ============================================================================
```
